### PR TITLE
allow statements; pass through syntax errors to repl module

### PR DESCRIPTION
**Pull request by forivall**
Mostly for node 0.10 compat, but this also allows multiline statements. Generally, just let repl handle the errors emitted during script parsing.

https://github.com/nodejs/node/blob/v0.10.40-release/lib/repl.js#L239

### CODE REVIEW

**Comment by StreetStrider** [comment]
As far as I remember, this was caused by some tab-completion errors.
9d07ef this commit introduces this changes. I presume if it will be turned off, error will return.
To reproduce, just use tab on partial expressions. (they will cause SyntaxError).

**Comment by forivall** [comment]
Which version of node? I couldn't reproduce on 0.10.41 or 4.4.1. In general, I see swallowing errors as a bad thing.

**Comment by StreetStrider** [comment]
I've tested this fix, looks like almost everything fine. Can you check `master` now?

**Comment by forivall** [comment]
Works fine

I don't know why you didn't just locally merge my commit 😐 ¯\_(ツ)_/¯

**Comment by StreetStrider** [comment]
I'm sorry, I don't like GitHub merges and PRs too much. I'm more confident with git CLI. It was simpler to replay changes. I would use merge for more complex PRs.

**Comment by StreetStrider** [comment]
`+ repl.js@2.3.6`

**Comment by forivall** [comment]
`git fetch git@github.com:forivall/repl.js fix-statements && git cherry-pick FETCH_HEAD`, fyi.

**Pull request closed without merging**
